name: static website hosting to s3 bucket

on: [push]

jobs:
    deploy-to-s3:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository Code
              uses: actions/checkout@v3

            - name: AWS Credetials
              uses: aws-actions/configure-aws-credentials@v2 
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-central-1   

            - name: Push To AWS S3 Bucket 
              run: aws s3 sync . s3://aws-s3-bucket-website-devops-exam    
